apiVersion: v1
kind: ConfigMap
metadata:
  name: ad-admin-service-config
  namespace: ad-admin
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_SERVER_PORT: "8089"
  EUREKA_URL: http://eureka-service.default.svc.cluster.local:8761/eureka
