apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ad-admin-service-secret
  namespace: ad-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: ad-admin-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ad-admin-service-secret
